# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170709_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='accepted',
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
