# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20170709_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='message',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
